spring.application.name=cafeteria-backend
spring.datasource.url=jdbc:postgresql://${DB_URL:dbnhyyrnnqoppwqnedvrgg.supabase.co}:${DB_PORT:5432}/${DB_NAME:postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:contraseña123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

server.port=${SERVER_PORT:8080}

jwt.secret=${JWT_SECRET:dGhpcyBpcyBhIGR1bW15IHNlY3JldCBrZXkgZm9yIHRlc3Rpbmc=}
jwt.expiration=${JWT_EXPIRATION:86400000}

supabase.url=${SUPABASE_URL:https://dbnhyyrnnqoppwqnedvrgg.supabase.co}
supabase.key=${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFzIiwiaWQiOiIxMjM0NTY3OC0xMjM0LTEyMzQtMTIzNC0xMjM0NTY3ODkwYWIiLCJ0aWVuZFNwcm9taXNlIjp0cnVlLCJpYXQiOjE2NDUxOTI4MTZ9.RYwTqtWBMVhyLhdSndT2GZhTQEkU5HbLrWcLItq5bYJc}
supabase.service-key=${SUPABASE_SERVICE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlkIjoiMTIzNDU2NzgtMTIzNC0xMjM0LTEyMzQtMTIzNDU2Nzg5MGFiIiwidGllblNwb3JtaXNlIjp0cnVlLCJpYXQiOjE2NDUxOTI4MTZ9.fhGkpG_2rT5q_rK3B1J8WqzZkV8WqhCkZ2r_vW2rT5q}

cors.allowed-origins=*

logging.level.com.utp.cafeteria=DEBUG
logging.level.org.springframework.security=DEBUG